### PR TITLE
67 bigmark table1

### LINKED ISSUE #67: [BUG]: `big.mark` formatting in `cell_suppression` does not work correctly for categorical variables
Affected function: `render_cell_suppression.categorical()`

There seems to be a small bug resulting in `big.mark = ","` not being applied correctly.
 
Example:
When running this code, the thousands separator is only applied to continuous & missing variables, but not to categorical variables. 
 
```
df <- data.table(income = c(rep(60000, 10000), rep(NA, 1000)), 
                 sex = c(rep("F", 5000), rep("M", 5000), rep(NA, 1000)))

table1(~ sex + income, 
       data = df,
       render.categorical = render_cell_suppression.categorical,
       render.continuous = render_cell_suppression.continuous,
       digits = 1,
       big.mark=","
)

```
table1

This seems to be a problem with `render_cell_suppression.categorical`. This code results in the expected output:
```
table1(~ sex + income, 
       data = df,
       #render.categorical = render_cell_suppression.categorical,
       render.continuous = render_cell_suppression.continuous,
       digits = 1,
       big.mark=","
)
```
table1_2

### PR DESCRIPTION
**Pull request by loffleraSMH**
Closes #67 

I’ve implemented some enhancement for each render function to allow for additional user inputs that are passed to `prettyNum`, which enables additional formatting that can be useful when presenting large numbers (e.g., big.mark = “,” to add comma thousands separator). I’ve tested all render functions to check if the updated code produces the expected output (see screenshot below) and made sure that nothing breaks. 

I also added a small bug fix for `digits` to be applied consistently to all outputs, including % missing.

The person reviewing the changes should perform some additional testing. The following code can be used as a starting point (you can comment/uncomment the different render functions to test each function's behavior): 

```
set.seed(3)
gender <- c(sample(c("M", "F"), size = 99995, replace = TRUE), rep(NA, times = 5))
exposure <- sample(
  c("pre-pandemic", "pandemic", "post-pandemic"), 
  size = 100000, replace = TRUE
)
income <- c(rnorm(90000, mean = 70000, sd = 5000), rep(NA, times = 10000))
condition <- sample(
  c("DVT", "CVD", "DM", "Pneumonia", "Dementia", NA), 
  size = 100000, replace = TRUE, prob = c(0.01, 0.20, 0.4, 0.35, 0.05, .01)
)
data <- data.frame(gender = gender, exposure = exposure, income = income, condition = condition)

table1(
  ~ gender + income + condition | exposure, 
  data = data, 
  render = render_cell_suppression.default, 
  digits = 2,
  big.mark = ",",
  #render.categorical = render_cell_suppression.categorical, # or: render_strict_cell_suppression.categorical,
  #render.continuous = render_cell_suppression.continuous
  #render.missing = render_cell_suppression.missing
  render.strat = render_cell_suppression.strat
)
```
Screenshot 2024-05-14 153132

### CODE REVIEW

File: R/cell_suppression.R [hunk 1]
```diff
@@ -134,7 +135,7 @@ render_cell_suppression.default <- function(
   if (is.logical(x)) x <- factor(x, levels = c(T, F), labels = c("Yes", "No"))
 
   if (is.factor(x) || is.character(x)) {
-    r <- do.call(render.categorical, list(x = x))
+    r <- do.call(render.categorical, c(list(x = x), list(...)))
```
Comment (vaakesan-SMH) [inline R/cell_suppression.R:138]: No functional difference but this would be more readable as `list(x = x, ...)` instead of `c(list(x = x), list(...))`

**Review by vaakesan-SMH — APPROVED** [review]
Tested on a few different examples, appears to work well and is pretty robust! Great implementation, thanks @loffleraSMH!

Trivial comment below, feel free to take or leave. Otherwise good to merge.

File: R/cell_suppression.R (hunk 1 above)
Comment (loffleraSMH) [reply R/cell_suppression.R]: Thanks for reviewing @vaakesan-SMH! Ah yes, good point. I fixed this now and will go ahead and merge.
